server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: ${LOKI_URL}
    external_labels:
      job: fastapi-task-manager

scrape_configs:
  - job_name: docker
    static_configs:
      - targets: [localhost]
        labels:
          job: docker
          __path__: /var/lib/docker/containers/*/*-json.log

    pipeline_stages:
      - docker:
          # Добавляем метки из лейблов Docker
          tag: ".+"
          drop_labels:
            - "com.docker.compose.oneoff"
            - "com.docker.compose.project"
            - "com.docker.compose.service"
            - "com.docker.compose.version"

      - json:
          expressions:
            level: level
            logger: logger
            message: message
            service: service
            thread: thread
            function: function
            file: file
            line: line

      # Добавляем метки для фильтрации
      - labels:
          job:
          service:
          level:
          logger:
          host:
          file:
          function:
